name: Ruby

on:
  push:

env:
  MERRIAM_WEBSTER_API_KEY: merriam_webster_api_key
  MERRIAM_WEBSTER_API_URL: https://www.dictionaryapi.com/api/v3/references/collegiate/json/
  SELENIUM_DRIVER: firefox
  SOURCES: google_translate merriam_webster

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.2.0'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake
